apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kwjapp
  name: game-2048-deploy
spec:
  selector:
    matchLabels:
      app: game-2048
  replicas: 3
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: game-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: kwjapp
  name: game-2048-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: game-2048
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kwjapp
  name: game-2048-ing
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: dongseo
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:383654655155:certificate/4fab9589-8d61-4cf5-a015-c691e26fe7ec
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    alb.ingress.kubernetes.io/group.name: dongseo
spec:
  ingressClassName: alb
  rules:
    - host: "luckyvanilla.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: "game-2048-svc"
                port: 
                  number: 80
